### ISSUE TITLE
responsive maken van app

### ISSUE THREAD

**Issue by samanthavz** [samanthavz/team-tech#13]
Ik ben van plan om de website iets meer responsive te maken als ik tijd heb. Als een van jullie hier goed in is kan je alvast een responsive branch aanmaken en hier en daar wat doen (de features en topics gaan voor, dus maak die eerst af!!!). Waarschijnlijk doe ik dit begin volgende week ofzo.

**Comment by zainuwachtig** [comment]
Moeten we het niet begin volgende week inleveren? :hushed:

**Comment by samanthavz** [comment]
Ja dinsdag ofzo, dus dan ga ik het maandag doen. Het is voor mij ook meer voor frontend ipv project tech, en die deadline staat later

**Comment by samanthavz** [comment]
ik heb nu een groot deel responsive en vind het zo wel goed. Ik zal het later pushen aangezien ik het voor me individuele gedeelte had geschreven. :)
