### ISSUE TITLE
Database URI error

### ISSUE THREAD

**Issue by zainuwachtig** [samanthavz/team-tech#6]
Ik krijg de error dat die de URI niet wilt parsen, weet iemand wat het kan zijn?

**Comment by jabirtisou** [comment]
Wat is de error?

**Comment by samanthavz** [comment]
stuur eens wat je in je .env hebt staan

**Comment by zainuwachtig** [comment]
![Uploading Schermafbeelding 2021-06-06 om 23.29.57.png…]()

**Comment by zainuwachtig** [comment]
<img width="1008" alt="Schermafbeelding 2021-06-06 om 23 29 57" src="https://user-images.githubusercontent.com/74155415/121027069-f727a080-c7a6-11eb-8288-4ea7ddaa40a8.png">

**Comment by jabirtisou** [comment]
DB_URI moet DB_CONNECT worden, dan moet t lukken!
