### ISSUE TITLE
Font fix

### ISSUE THREAD

**Issue by samanthavz** [samanthavz/team-tech#8]
Misschien hebben jullie het al gezien, maar kan iemand naar de fonts kijken? Hij werkt nu volgensmij niet op mac/safari en andere browser. Wel bij mij in chrome. Maak hiervoor even een font branch aan!! Er is een font.css file waar ik de font in heb staan.

**Comment by zainuwachtig** [comment]
Bij mij werkt die op mac/safari!

**Comment by samanthavz** [comment]
![image](https://user-images.githubusercontent.com/58736005/121231629-e7848680-c890-11eb-9d47-ad3a34040d70.png)
Is dit de font die je ziet? Ik dacht nmlk dat ik juist bij jou op school zag dat de fonts anders was

**Comment by zainuwachtig** [comment]
Oh nee, dan zie ik hem in zowel chrome als safari niet. Ik zal ff checken of ik het kan fixen

**Comment by samanthavz** [comment]
looking good ik close deze issue
